name: allure-report

on:
  release:
    types:
      - created
  push:
    branches-ignore:
      - '!master'
      
env:
  DOTNET_VERSION: '6.0.x'
  TEST_ENVIRONMENT: Development

jobs:
  allure:
    name: Run tests and publish report
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api-test-suite
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ntiwari-z/api-test-suite # Test suite repo name
          token: ${{ secrets.PAT }} # Github private access token
          path: api-test-suite
  
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
    
      - name: Prepare Allure history # Step to prepare Allure history directory
        run: |
          cd ..
          mkdir -p allure-results
          cd allure-results
          mkdir -p history

      - name: Run Tests
        run: dotnet test --no-restore --verbosity normal -e TEST_ENVIRONMENT=${{ env.TEST_ENVIRONMENT }}

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          repository: ntiwari-z/api-test-suite
          token: ${{ secrets.PAT }}
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT }}
          external_repository: ntiwari-z/api-test-suite
          publish_branch: gh-pages
          publish_dir: allure-history