name: allure-report

on:
  release:
    types:
      - created
  push:
    branches-ignore:
      - '!master'
      
env:
  DOTNET_VERSION: '6.0.x'
  TEST_ENVIRONMENT: Development
  HOTELAPI_BASEURL: https://svc-api.ath-dev.com/api/hotel
  TESTSUITE_REPO: ntiwari-z/api-test-suite

jobs:
  allure:
    name: Run tests and publish report
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api-test-suite
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.TESTSUITE_REPO }} # Test suite repo name
          token: ${{ secrets.PAT }} # Github private access token
          path: api-test-suite
  
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
    
      - name: Run Tests
        run: dotnet test --no-restore --verbosity normal -e TEST_ENVIRONMENT=${{ env.TEST_ENVIRONMENT }} -e AppSettings__HotelApiBaseUrl=${{ env.HOTELAPI_BASEURL }}

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          repository: ${{ env.TESTSUITE_REPO }} # Test suite repo name
          token: ${{ secrets.PAT }} # Github private access token
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: api-test-suite/Tests/bin/Debug/net6.0/allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT }} # Github private access token
          external_repository: ${{ env.TESTSUITE_REPO }} # Test suite repo name
          publish_branch: gh-pages
          publish_dir: allure-history